# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ni_nfvo.models.base_model_ import Model
from ni_nfvo import util


class RouteUpdateSpec(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, sfcr_ids: List[str]=None, vnf_instance_ids: List[List[str]]=None):  # noqa: E501
        """RouteUpdateSpec - a model defined in Swagger

        :param sfcr_ids: The sfcr_ids of this RouteUpdateSpec.  # noqa: E501
        :type sfcr_ids: List[str]
        :param vnf_instance_ids: The vnf_instance_ids of this RouteUpdateSpec.  # noqa: E501
        :type vnf_instance_ids: List[List[str]]
        """
        self.swagger_types = {
            'sfcr_ids': List[str],
            'vnf_instance_ids': List[List[str]]
        }

        self.attribute_map = {
            'sfcr_ids': 'sfcr_ids',
            'vnf_instance_ids': 'vnf_instance_ids'
        }

        self._sfcr_ids = sfcr_ids
        self._vnf_instance_ids = vnf_instance_ids

    @classmethod
    def from_dict(cls, dikt) -> 'RouteUpdateSpec':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RouteUpdateSpec of this RouteUpdateSpec.  # noqa: E501
        :rtype: RouteUpdateSpec
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sfcr_ids(self) -> List[str]:
        """Gets the sfcr_ids of this RouteUpdateSpec.


        :return: The sfcr_ids of this RouteUpdateSpec.
        :rtype: List[str]
        """
        return self._sfcr_ids

    @sfcr_ids.setter
    def sfcr_ids(self, sfcr_ids: List[str]):
        """Sets the sfcr_ids of this RouteUpdateSpec.


        :param sfcr_ids: The sfcr_ids of this RouteUpdateSpec.
        :type sfcr_ids: List[str]
        """

        self._sfcr_ids = sfcr_ids

    @property
    def vnf_instance_ids(self) -> List[List[str]]:
        """Gets the vnf_instance_ids of this RouteUpdateSpec.

        each sub-list represent a node on the traffic path. each node is a list of vnf instances, where traffic are load-balanced  # noqa: E501

        :return: The vnf_instance_ids of this RouteUpdateSpec.
        :rtype: List[List[str]]
        """
        return self._vnf_instance_ids

    @vnf_instance_ids.setter
    def vnf_instance_ids(self, vnf_instance_ids: List[List[str]]):
        """Sets the vnf_instance_ids of this RouteUpdateSpec.

        each sub-list represent a node on the traffic path. each node is a list of vnf instances, where traffic are load-balanced  # noqa: E501

        :param vnf_instance_ids: The vnf_instance_ids of this RouteUpdateSpec.
        :type vnf_instance_ids: List[List[str]]
        """

        self._vnf_instance_ids = vnf_instance_ids
