---
kind: pipeline
type: docker
name: ni-mon-tests__nightly__python-3.5__prod

steps:
- name: config target
  image: python:3.5
  environment:
    MONITORING_HOST_PROD:
      from_secret: monitoring_host_prod
  commands:
  - cd tests/config
  - cp config.yaml.example config.yaml
  - sed -i "s/<ni_mon_server_addr>/$MONITORING_HOST_PROD/g" config.yaml
  - sed -i "s/<ni_ni_nfvo_addr>/$MONITORING_HOST_PROD/g" config.yaml
- name: test with python 3
  image: python:3.5
  commands:
  - pip install -r requirements_ni_tests.txt
  - pytest tests/test_ni_mon.py

trigger:
  branch:
  - master
  event:
  - cron

