---
swagger: "2.0"
info:
  description: "NFVO module service for the NI project."
  version: "1.0.0"
  title: "NI-NFVO"
  contact:
    email: "vantu.bkhn@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
schemes:
- "http"
paths:
  /sfcrs:
    get:
      tags:
      - "sfcr"
      summary: "Get currently active Sfc requests."
      operationId: "get_sfcrs"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Success."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Sfcr"
      x-swagger-router-controller: "ni_nfvo.controllers.sfcr_controller"
    post:
      tags:
      - "sfcr"
      summary: "Add new Sfc request. return sfcr ID if success"
      operationId: "add_sfcr"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "sfcr_spec"
        description: "Sfc request object to be added."
        required: true
        schema:
          $ref: "#/definitions/SfcrSpec"
      responses:
        "200":
          description: "Success."
          schema:
            type: "string"
      x-swagger-router-controller: "ni_nfvo.controllers.sfcr_controller"
  /sfcrs/{id}:
    delete:
      tags:
      - "sfcr"
      summary: "Delete a sfcr."
      description: ""
      operationId: "del_sfcr"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "sfc id"
        required: true
        type: "string"
      responses:
        "200":
          description: "Success."
      x-swagger-router-controller: "ni_nfvo.controllers.sfcr_controller"
  /sfcs:
    get:
      tags:
      - "sfc"
      summary: "Get current sfc information, i.e., list of all active Sfcrs including\
        \ their paths."
      description: ""
      operationId: "get_sfcs"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Success."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Sfc"
      x-swagger-router-controller: "ni_nfvo.controllers.sfc_controller"
    post:
      tags:
      - "sfc"
      summary: "Create a Sfc. Return sfc ID if success."
      description: ""
      operationId: "set_sfc"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "sfc_spec"
        description: "Sfc information including Sfcr ID and vnf instance ids."
        required: true
        schema:
          $ref: "#/definitions/SfcSpec"
      responses:
        "200":
          description: "Success."
          schema:
            type: "string"
        "400":
          description: "Invalid parameters supplied."
      x-swagger-router-controller: "ni_nfvo.controllers.sfc_controller"
  /sfcs/{id}:
    put:
      tags:
      - "sfc"
      summary: "Update a new sfc path or new sfcrs."
      description: ""
      operationId: "update_sfc"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "sfc id"
        required: true
        type: "string"
      - in: "body"
        name: "sfc_update_spec"
        description: "Sfc Update info."
        required: true
        schema:
          $ref: "#/definitions/SfcUpdateSpec"
      responses:
        "200":
          description: "Success."
          schema:
            type: "string"
      x-swagger-router-controller: "ni_nfvo.controllers.sfc_controller"
    delete:
      tags:
      - "sfc"
      summary: "Delete a Sfc."
      description: ""
      operationId: "del_sfc"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "sfc id"
        required: true
        type: "string"
      responses:
        "200":
          description: "Success."
      x-swagger-router-controller: "ni_nfvo.controllers.sfc_controller"
  /vnfs:
    post:
      tags:
      - "vnf"
      summary: "Instantiate an instance of a Vnf flavor on a given node. Return vnf\
        \ ID if success"
      operationId: "deploy_vnf"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "vnf_spec"
        description: "Flavor of Vnf instance to be deployed as well as the target\
          \ node."
        required: true
        schema:
          $ref: "#/definitions/VnfSpec"
      responses:
        "200":
          description: "Success."
          schema:
            type: "string"
      x-swagger-router-controller: "ni_nfvo.controllers.vnf_controller"
  /vnfs/{id}:
    delete:
      tags:
      - "vnf"
      summary: "Destroy a Vnf instance."
      description: ""
      operationId: "destroy_vnf"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "vnf id"
        required: true
        type: "string"
      responses:
        "200":
          description: "Success."
      x-swagger-router-controller: "ni_nfvo.controllers.vnf_controller"
  /vnfs/{id}/shutdown:
    post:
      tags:
      - "vnf"
      summary: "Shut down a Vnf instance."
      description: ""
      operationId: "shutdown_vnf"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of Vnf instance to be shut down."
        required: true
        type: "string"
      responses:
        "200":
          description: "Success."
      x-swagger-router-controller: "ni_nfvo.controllers.vnf_controller"
definitions:
  SfcrSpec:
    type: "object"
    required:
    - "source_client"
    properties:
      name:
        type: "string"
      source_client:
        type: "string"
        description: "the id of the source VM (not Vnf)"
      destination_client:
        type: "string"
        description: "the id of the destination VM (not Vnf)"
      src_ip_prefix:
        type: "string"
      dst_ip_prefix:
        type: "string"
      src_port_min:
        type: "integer"
        format: "int32"
      src_port_max:
        type: "integer"
        format: "int32"
      dst_port_min:
        type: "integer"
        format: "int32"
      dst_port_max:
        type: "integer"
        format: "int32"
      proto:
        type: "string"
      bw:
        type: "integer"
        format: "int32"
        description: "bandwidth requirement of the sfcr"
      delay:
        type: "integer"
        format: "int32"
        description: "delay requirement of the sfcr"
      duration:
        type: "integer"
        format: "int32"
        description: "sfcr running duration"
      nf_chain:
        type: "array"
        description: "the type of Vnfs in the path (e.g.: fw, ids, nat, etc.)."
        items:
          type: "string"
    description: "Specification to create new Sfc request. src/dst ip prefix, src/dst\
      \ port min/max, proto are for traffic classification"
    example:
      src_port_max: 6
      source_client: "source_client"
      destination_client: "destination_client"
      dst_ip_prefix: "dst_ip_prefix"
      nf_chain:
      - "nf_chain"
      - "nf_chain"
      src_ip_prefix: "src_ip_prefix"
      src_port_min: 0
      duration: 7
      dst_port_min: 1
      delay: 2
      bw: 5
      proto: "proto"
      name: "name"
      dst_port_max: 5
  Sfcr:
    type: "object"
    properties:
      id:
        type: "string"
      arrivaltime:
        type: "string"
        format: "date-time"
      name:
        type: "string"
      source_client:
        type: "string"
        description: "the id of the source VM (not Vnf)"
      destination_client:
        type: "string"
        description: "the id of the destination VM (not Vnf)"
      src_ip_prefix:
        type: "string"
      dst_ip_prefix:
        type: "string"
      src_port_min:
        type: "integer"
        format: "int32"
      src_port_max:
        type: "integer"
        format: "int32"
      dst_port_min:
        type: "integer"
        format: "int32"
      dst_port_max:
        type: "integer"
        format: "int32"
      proto:
        type: "string"
      bw:
        type: "integer"
        format: "int32"
        description: "bandwidth requirement of the sfcr"
      delay:
        type: "integer"
        format: "int32"
        description: "delay requirement of the sfcr"
      duration:
        type: "integer"
        format: "int32"
        description: "sfcr running duration"
      nf_chain:
        type: "array"
        description: "the type of Vnfs in the path (e.g.: fw, ids, nat, etc.)."
        items:
          type: "string"
    description: "Sfc request."
    example:
      src_port_max: 6
      source_client: "source_client"
      destination_client: "destination_client"
      dst_ip_prefix: "dst_ip_prefix"
      nf_chain:
      - "nf_chain"
      - "nf_chain"
      src_ip_prefix: "src_ip_prefix"
      src_port_min: 0
      duration: 7
      dst_port_min: 1
      delay: 2
      bw: 5
      proto: "proto"
      arrivaltime: "2000-01-23T04:56:07.000+00:00"
      name: "name"
      id: "id"
      dst_port_max: 5
  SfcSpec:
    type: "object"
    required:
    - "sfcr_ids"
    - "vnf_instance_ids"
    properties:
      sfc_name:
        type: "string"
      sfcr_ids:
        type: "array"
        items:
          type: "string"
      vnf_instance_ids:
        type: "array"
        description: "list of list of vnf id(s). Each sub-list is a node in traffic\
          \ path, where traffic are load-balanced between Vnfs in the node. Each E.g.:\
          \ [[A,B], [C], [D]] : traffic go to [A, B] node (load-balanced between A\
          \ and B), then go to C, then go to D."
        items:
          type: "array"
          items:
            type: "string"
      is_symmetric:
        type: "boolean"
    description: "Specficiation to create Sfc information for given Sfcr ID(s)"
    example:
      vnf_instance_ids:
      - - "vnf_instance_ids"
        - "vnf_instance_ids"
      - - "vnf_instance_ids"
        - "vnf_instance_ids"
      is_symmetric: true
      sfc_name: "sfc_name"
      sfcr_ids:
      - "sfcr_ids"
      - "sfcr_ids"
  Sfc:
    type: "object"
    properties:
      id:
        type: "string"
      sfc_name:
        type: "string"
      sfcr_ids:
        type: "array"
        items:
          type: "string"
      vnf_instance_ids:
        type: "array"
        description: "list of list of vnf id(s). Each sub-list is a node in traffic\
          \ path, where traffic are load-balanced between Vnfs in the node. Each E.g.:\
          \ [[A,B], [C], [D]] : traffic go to [A, B] node (load-balanced between A\
          \ and B), then go to C, then go to D."
        items:
          type: "array"
          items:
            type: "string"
      is_symmetric:
        type: "boolean"
    description: "Detailed Sfc information."
    example:
      vnf_instance_ids:
      - - "vnf_instance_ids"
        - "vnf_instance_ids"
      - - "vnf_instance_ids"
        - "vnf_instance_ids"
      is_symmetric: true
      sfc_name: "sfc_name"
      id: "id"
      sfcr_ids:
      - "sfcr_ids"
      - "sfcr_ids"
  SfcUpdateSpec:
    type: "object"
    properties:
      sfcr_ids:
        type: "array"
        items:
          type: "string"
      vnf_instance_ids:
        type: "array"
        description: "each sub-list represent a node on the traffic path. each node\
          \ is a list of vnf instances, where traffic are load-balanced"
        items:
          type: "array"
          items:
            type: "string"
    description: "Specification to update the path of a sfc."
    example:
      vnf_instance_ids:
      - - "vnf_instance_ids"
        - "vnf_instance_ids"
      - - "vnf_instance_ids"
        - "vnf_instance_ids"
      sfcr_ids:
      - "sfcr_ids"
      - "sfcr_ids"
  VnfSpec:
    type: "object"
    required:
    - "flavor_id"
    properties:
      flavor_id:
        type: "string"
      node_name:
        type: "string"
        description: "name of the compute node where Vnf will be deployed"
      vnf_name:
        type: "string"
      user_data:
        type: "string"
        description: "configuration to pass to the Vnf at boot (e.g., cloud-init)"
      image_id:
        type: "string"
        description: "custom OS image id other than the default id from falvor"
    description: "specification to deploy Vnf."
    example:
      flavor_id: "flavor_id"
      node_name: "node_name"
      vnf_name: "vnf_name"
      user_data: "user_data"
      image_id: "image_id"
externalDocs:
  description: "Find out more about DPNM NI."
  url: "http://dpnm.postech.ac.kr/"
