# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ni_mon.models.base_model_ import Model
from ni_mon import util


class MeasurementTypes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, measurements: List[str]=None):  # noqa: E501
        """MeasurementTypes - a model defined in Swagger

        :param measurements: The measurements of this MeasurementTypes.  # noqa: E501
        :type measurements: List[str]
        """
        self.swagger_types = {
            'measurements': List[str]
        }

        self.attribute_map = {
            'measurements': 'measurements'
        }

        self._measurements = measurements

    @classmethod
    def from_dict(cls, dikt) -> 'MeasurementTypes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MeasurementTypes of this MeasurementTypes.  # noqa: E501
        :rtype: MeasurementTypes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def measurements(self) -> List[str]:
        """Gets the measurements of this MeasurementTypes.


        :return: The measurements of this MeasurementTypes.
        :rtype: List[str]
        """
        return self._measurements

    @measurements.setter
    def measurements(self, measurements: List[str]):
        """Sets the measurements of this MeasurementTypes.


        :param measurements: The measurements of this MeasurementTypes.
        :type measurements: List[str]
        """

        self._measurements = measurements
