# coding: utf-8

"""
    NI-NFVO

    NFVO module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: vantu.bkhn@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ni_nfvo_client
from ni_nfvo_client.api.sfcr_api import SfcrApi  # noqa: E501
from ni_nfvo_client.rest import ApiException


class TestSfcrApi(unittest.TestCase):
    """SfcrApi unit test stubs"""

    def setUp(self):
        self.api = ni_nfvo_client.api.sfcr_api.SfcrApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_sfcr(self):
        """Test case for add_sfcr

        Add new Sfc request. return sfcr ID if success  # noqa: E501
        """
        pass

    def test_del_sfcr(self):
        """Test case for del_sfcr

        Delete a sfcr.  # noqa: E501
        """
        pass

    def test_get_sfcrs(self):
        """Test case for get_sfcrs

        Get currently active Sfc requests.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
