# coding: utf-8

"""
    NI-NFVO

    NFVO module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: vantu.bkhn@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ni_nfvo_client
from ni_nfvo_client.api.sfc_api import SfcApi  # noqa: E501
from ni_nfvo_client.rest import ApiException


class TestSfcApi(unittest.TestCase):
    """SfcApi unit test stubs"""

    def setUp(self):
        self.api = ni_nfvo_client.api.sfc_api.SfcApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_del_sfc(self):
        """Test case for del_sfc

        Delete a Sfc.  # noqa: E501
        """
        pass

    def test_get_sfcs(self):
        """Test case for get_sfcs

        Get current sfc information, i.e., list of all active Sfcrs including their paths.  # noqa: E501
        """
        pass

    def test_set_sfc(self):
        """Test case for set_sfc

        Create a Sfc. Return sfc ID if success.  # noqa: E501
        """
        pass

    def test_update_sfc(self):
        """Test case for update_sfc

        Update a new sfc path or new sfcrs.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
