# coding: utf-8

"""
    NI-NFVO

    NFVO module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: vantu.bkhn@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import nfvo_client
from nfvo_client.api.vnf_api import VnfApi  # noqa: E501
from nfvo_client.rest import ApiException


class TestVnfApi(unittest.TestCase):
    """VnfApi unit test stubs"""

    def setUp(self):
        self.api = nfvo_client.api.vnf_api.VnfApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deploy_vnf(self):
        """Test case for deploy_vnf

        Instantiate an instance of a VNF flavor on a given node.  # noqa: E501
        """
        pass

    def test_destroy_vnf(self):
        """Test case for destroy_vnf

        Destroy a VNF instance.  # noqa: E501
        """
        pass

    def test_shutdown_vnf(self):
        """Test case for shutdown_vnf

        Shut down a VNF instance.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
