# coding: utf-8

"""
    NI-NFVO

    NFVO module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: vantu.bkhn@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import nfvo_client
from nfvo_client.models.route import Route  # noqa: E501
from nfvo_client.rest import ApiException


class TestRoute(unittest.TestCase):
    """Route unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoute(self):
        """Test Route"""
        # FIXME: construct object with mandatory attributes with example values
        # model = nfvo_client.models.route.Route()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
