# coding: utf-8

"""
    NI-NFVO

    NFVO module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: vantu.bkhn@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ni_nfvo_client
from ni_nfvo_client.models.sfc import Sfc  # noqa: E501
from ni_nfvo_client.rest import ApiException


class TestSfc(unittest.TestCase):
    """Sfc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSfc(self):
        """Test Sfc"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ni_nfvo_client.models.sfc.Sfc()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
