# coding: utf-8

"""
    NI-NFVO

    NFVO module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: vantu.bkhn@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import nfvo_client
from nfvo_client.api.route_api import RouteApi  # noqa: E501
from nfvo_client.rest import ApiException


class TestRouteApi(unittest.TestCase):
    """RouteApi unit test stubs"""

    def setUp(self):
        self.api = nfvo_client.api.route_api.RouteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_del_route(self):
        """Test case for del_route

        Delete a Route.  # noqa: E501
        """
        pass

    def test_get_routes(self):
        """Test case for get_routes

        Get current route information, i.e., list of all active SFCRs including their paths.  # noqa: E501
        """
        pass

    def test_set_route(self):
        """Test case for set_route

        Route a request via the provided route. Return route id if success (which also means input route id is ommitted).  # noqa: E501
        """
        pass

    def test_update_route(self):
        """Test case for update_route

        Update a new route path or new sfcrs.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
