# coding: utf-8

"""
    NI-Mon

    Monitoring module for NI project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: vantu.bkhn@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class VNFInstance(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'status': 'str',
        'flavor_id': 'str',
        'node_id': 'str',
        'ports': 'list[NetworkPort]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'status': 'status',
        'flavor_id': 'flavor_id',
        'node_id': 'node_id',
        'ports': 'ports'
    }

    def __init__(self, id=None, name=None, status=None, flavor_id=None, node_id=None, ports=None):  # noqa: E501
        """VNFInstance - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._status = None
        self._flavor_id = None
        self._node_id = None
        self._ports = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if status is not None:
            self.status = status
        if flavor_id is not None:
            self.flavor_id = flavor_id
        if node_id is not None:
            self.node_id = node_id
        if ports is not None:
            self.ports = ports

    @property
    def id(self):
        """Gets the id of this VNFInstance.  # noqa: E501


        :return: The id of this VNFInstance.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this VNFInstance.


        :param id: The id of this VNFInstance.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this VNFInstance.  # noqa: E501


        :return: The name of this VNFInstance.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VNFInstance.


        :param name: The name of this VNFInstance.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def status(self):
        """Gets the status of this VNFInstance.  # noqa: E501

        state of VNF VM. (ACTIVE, SHUTOFF, ERROR, etc.)  # noqa: E501

        :return: The status of this VNFInstance.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this VNFInstance.

        state of VNF VM. (ACTIVE, SHUTOFF, ERROR, etc.)  # noqa: E501

        :param status: The status of this VNFInstance.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def flavor_id(self):
        """Gets the flavor_id of this VNFInstance.  # noqa: E501


        :return: The flavor_id of this VNFInstance.  # noqa: E501
        :rtype: str
        """
        return self._flavor_id

    @flavor_id.setter
    def flavor_id(self, flavor_id):
        """Sets the flavor_id of this VNFInstance.


        :param flavor_id: The flavor_id of this VNFInstance.  # noqa: E501
        :type: str
        """

        self._flavor_id = flavor_id

    @property
    def node_id(self):
        """Gets the node_id of this VNFInstance.  # noqa: E501


        :return: The node_id of this VNFInstance.  # noqa: E501
        :rtype: str
        """
        return self._node_id

    @node_id.setter
    def node_id(self, node_id):
        """Sets the node_id of this VNFInstance.


        :param node_id: The node_id of this VNFInstance.  # noqa: E501
        :type: str
        """

        self._node_id = node_id

    @property
    def ports(self):
        """Gets the ports of this VNFInstance.  # noqa: E501


        :return: The ports of this VNFInstance.  # noqa: E501
        :rtype: list[NetworkPort]
        """
        return self._ports

    @ports.setter
    def ports(self, ports):
        """Sets the ports of this VNFInstance.


        :param ports: The ports of this VNFInstance.  # noqa: E501
        :type: list[NetworkPort]
        """

        self._ports = ports

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VNFInstance, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VNFInstance):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
