# coding: utf-8

# flake8: noqa
"""
    NI-NFVO

    NFVO module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: vantu.bkhn@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from nfvo_client.models.body import Body
from nfvo_client.models.route import Route
from nfvo_client.models.route_update import RouteUpdate
from nfvo_client.models.sfcr import SFCR
