# coding: utf-8

"""
    NI-NFVO

    NFVO module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: vantu.bkhn@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RouteUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sfcr_ids': 'list[str]',
        'vnf_instance_ids': 'list[list[str]]'
    }

    attribute_map = {
        'sfcr_ids': 'sfcr_ids',
        'vnf_instance_ids': 'vnf_instance_ids'
    }

    def __init__(self, sfcr_ids=None, vnf_instance_ids=None):  # noqa: E501
        """RouteUpdate - a model defined in Swagger"""  # noqa: E501

        self._sfcr_ids = None
        self._vnf_instance_ids = None
        self.discriminator = None

        if sfcr_ids is not None:
            self.sfcr_ids = sfcr_ids
        if vnf_instance_ids is not None:
            self.vnf_instance_ids = vnf_instance_ids

    @property
    def sfcr_ids(self):
        """Gets the sfcr_ids of this RouteUpdate.  # noqa: E501


        :return: The sfcr_ids of this RouteUpdate.  # noqa: E501
        :rtype: list[str]
        """
        return self._sfcr_ids

    @sfcr_ids.setter
    def sfcr_ids(self, sfcr_ids):
        """Sets the sfcr_ids of this RouteUpdate.


        :param sfcr_ids: The sfcr_ids of this RouteUpdate.  # noqa: E501
        :type: list[str]
        """

        self._sfcr_ids = sfcr_ids

    @property
    def vnf_instance_ids(self):
        """Gets the vnf_instance_ids of this RouteUpdate.  # noqa: E501

        each sub-list represent a node on the traffic path. each node is a list of vnf instances, where traffic are load-balanced  # noqa: E501

        :return: The vnf_instance_ids of this RouteUpdate.  # noqa: E501
        :rtype: list[list[str]]
        """
        return self._vnf_instance_ids

    @vnf_instance_ids.setter
    def vnf_instance_ids(self, vnf_instance_ids):
        """Sets the vnf_instance_ids of this RouteUpdate.

        each sub-list represent a node on the traffic path. each node is a list of vnf instances, where traffic are load-balanced  # noqa: E501

        :param vnf_instance_ids: The vnf_instance_ids of this RouteUpdate.  # noqa: E501
        :type: list[list[str]]
        """

        self._vnf_instance_ids = vnf_instance_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RouteUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RouteUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
